import Link from "next/link";
import { notFound } from "next/navigation";
import { findCompanyById } from "@/lib/company-repository";

const money = (value: number | null) => value === null ? "Not available" : `$${Math.round(value).toLocaleString()}`;

export default async function CompanyDetailPage({ params }: { params: Promise<{ id: string }> }) {
    const company = await findCompanyById((await params).id);
    if (!company) notFound();
    const stats = company.intelligence;
    const maxBucket = Math.max(...stats.distribution.map((bucket) => bucket.count), 1);

    return <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-blue-700">Company Intelligence</p><h1 className="text-3xl font-bold">{company.name}</h1><p className="mt-1 text-sm text-gray-600">{company.industry ?? "Industry not specified"} · {stats.recordCount} compensation records</p></div><Link href="/companies" className="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm hover:bg-gray-100">Back to companies</Link></div>
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Median TC", money(stats.medianTotalCompensation)], ["Lowest TC", money(stats.lowestTotalCompensation)], ["Highest TC", money(stats.highestTotalCompensation)], ["Median base", money(stats.medianBaseSalary)]].map(([label, value]) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</section>
        <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Compensation distribution</h2><p className="mt-1 text-sm text-gray-500">Based on {stats.recordCount} reported records.</p><div className="mt-5 space-y-4">{stats.distribution.map((bucket) => <div key={bucket.bucket} className="flex items-center gap-3 text-sm"><span className="w-28">{bucket.bucket}</span><div className="h-5 flex-1 rounded bg-gray-100"><div className="h-5 rounded bg-blue-600" style={{ width: `${(bucket.count / maxBucket) * 100}%` }} /></div><span className="w-8 text-right">{bucket.count}</span></div>)}</div></section><section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Pay mix</h2><p className="mt-1 text-sm text-gray-500">Average reported components.</p><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><p className="text-sm text-gray-500">Base</p><p className="mt-1 font-semibold">{money(stats.averageBaseSalary)}</p></div><div><p className="text-sm text-gray-500">Bonus</p><p className="mt-1 font-semibold">{money(stats.averageBonus)}</p></div><div><p className="text-sm text-gray-500">Stock</p><p className="mt-1 font-semibold">{money(stats.averageStock)}</p></div></div>{stats.percentiles ? <div className="mt-6 border-t border-gray-100 pt-4 text-sm"><h3 className="font-semibold">TC percentiles</h3><div className="mt-2 flex justify-between"><span>25th: {money(stats.percentiles.p25)}</span><span>50th: {money(stats.percentiles.p50)}</span><span>75th: {money(stats.percentiles.p75)}</span></div></div> : <p className="mt-6 border-t border-gray-100 pt-4 text-sm text-gray-500">Percentiles require at least 5 records.</p>}</section></div>
        <section className="mt-6 grid gap-6 md:grid-cols-3"><div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Common roles</h2><ul className="mt-3 space-y-2 text-sm">{stats.commonRoles.map((item) => <li key={item.name} className="flex justify-between"><span>{item.name}</span><span className="text-gray-500">{item.count}</span></li>)}</ul></div><div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Common levels</h2><ul className="mt-3 space-y-2 text-sm">{stats.commonLevels.map((item) => <li key={item.name} className="flex justify-between"><span>{item.name}</span><span className="text-gray-500">{item.count}</span></li>)}</ul></div><div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Locations</h2><ul className="mt-3 space-y-2 text-sm">{stats.locations.map((item) => <li key={item.name} className="flex justify-between"><span>{item.name}</span><span className="text-gray-500">{item.count}</span></li>)}</ul></div></section>
    </main>;
}
