import { CompensationRecord } from "@/lib/types";
import { normalizeCompanyName } from "@/lib/company";
import { calculateTotalCompensation } from "@/lib/validation";

export const salaryRecords: CompensationRecord[] = [
    {
        id: "r1",
        company: "Google LLC",
        normalizedCompany: "Google",
        role: "Software Engineer",
        level: "L3",
        location: "Seattle, WA",
        experience: 2,
        baseSalary: 185000,
        bonus: 18000,
        equity: 42000,
        totalCompensation: calculateTotalCompensation(185000, 18000, 42000),
        currency: "USD",
        source: "public",
        createdAt: "2025-01-15T00:00:00.000Z",
    },
    {
        id: "r2",
        company: "Google Inc.",
        normalizedCompany: "Google",
        role: "Software Engineer",
        level: "L3",
        location: "New York, NY",
        experience: 2,
        baseSalary: 178000,
        bonus: 16000,
        equity: 39000,
        totalCompensation: calculateTotalCompensation(178000, 16000, 39000),
        currency: "USD",
        source: "public",
        createdAt: "2025-01-16T00:00:00.000Z",
    },
    {
        id: "r3",
        company: "Microsoft",
        normalizedCompany: "Microsoft",
        role: "Senior Software Engineer",
        level: "L63",
        location: "Redmond, WA",
        experience: 5,
        baseSalary: 220000,
        bonus: 26000,
        equity: 64000,
        totalCompensation: calculateTotalCompensation(220000, 26000, 64000),
        currency: "USD",
        source: "public",
        createdAt: "2025-02-10T00:00:00.000Z",
    },
    {
        id: "r4",
        company: "Amazon",
        normalizedCompany: "Amazon",
        role: "Product Manager",
        level: "L5",
        location: "Seattle, WA",
        experience: 4,
        baseSalary: 196000,
        bonus: 23000,
        equity: 51000,
        totalCompensation: calculateTotalCompensation(196000, 23000, 51000),
        currency: "USD",
        source: "public",
        createdAt: "2025-02-12T00:00:00.000Z",
    },
    {
        id: "r5",
        company: "Meta Platforms",
        normalizedCompany: "Meta",
        role: "Data Engineer",
        level: "E4",
        location: "Menlo Park, CA",
        experience: 3,
        baseSalary: 205000,
        bonus: 24000,
        equity: 70000,
        totalCompensation: calculateTotalCompensation(205000, 24000, 70000),
        currency: "USD",
        source: "public",
        createdAt: "2025-02-20T00:00:00.000Z",
    },
    {
        id: "r6",
        company: "Stripe",
        normalizedCompany: "Stripe",
        role: "Backend Engineer",
        level: "L3",
        location: "San Francisco, CA",
        experience: 2,
        baseSalary: 172000,
        bonus: 15000,
        equity: 48000,
        totalCompensation: calculateTotalCompensation(172000, 15000, 48000),
        currency: "USD",
        source: "public",
        createdAt: "2025-02-05T00:00:00.000Z",
    },
    {
        id: "r7",
        company: "Apple Inc",
        normalizedCompany: "Apple",
        role: "Machine Learning Engineer",
        level: "M2",
        location: "Cupertino, CA",
        experience: 4,
        baseSalary: 210000,
        bonus: 22000,
        equity: 77000,
        totalCompensation: calculateTotalCompensation(210000, 22000, 77000),
        currency: "USD",
        source: "internal",
        createdAt: "2025-03-08T00:00:00.000Z",
    },
    {
        id: "r8",
        company: "Netflix",
        normalizedCompany: "Netflix",
        role: "Senior Product Manager",
        level: "P4",
        location: "Los Gatos, CA",
        experience: 6,
        baseSalary: 235000,
        bonus: 30000,
        equity: 98000,
        totalCompensation: calculateTotalCompensation(235000, 30000, 98000),
        currency: "USD",
        source: "partner",
        createdAt: "2025-03-18T00:00:00.000Z",
    },
    {
        id: "r9",
        company: "Airbnb",
        normalizedCompany: "Airbnb",
        role: "Staff Engineer",
        level: "S2",
        location: "San Francisco, CA",
        experience: 7,
        baseSalary: 245000,
        bonus: 27000,
        equity: 115000,
        totalCompensation: calculateTotalCompensation(245000, 27000, 115000),
        currency: "USD",
        source: "public",
        createdAt: "2025-04-08T00:00:00.000Z",
    },
];

export function seedNormalizedRecords(): CompensationRecord[] {
    return salaryRecords.map((record) => ({
        ...record,
        normalizedCompany: normalizeCompanyName(record.company),
    }));
}

export function getRecordsByCompany(company: string) {
    return salaryRecords.filter((record) => record.normalizedCompany === normalizeCompanyName(company));
}
